<a href="https://colab.research.google.com/github/lipeffl/PythonNumpy/blob/main/Python3NumpyAula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
meuArray = np.array(minhaLista) #transformar lista em array
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [ ]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
array1 = np.array(range(9)) #criando um array diretamente com range
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array2 = np.arange(9) #faz como na celula 6 sem usar "listrange"
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array3 = np.arange(0, 10, 0.5) #start, stop, step
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
#arredondano valores obtidos
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [ ]:
array3 = np.arange(0, 10, 0.5, dtype=int) ##não entendi## se colocar 1.5 o stop fica no 6 pq??
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
array5 = np.arange(12.)
array5

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
#verificando tipo do objeto
type(array4) #tipo de objeto

numpy.ndarray

In [ ]:
array4.dtype #tipos dos elementos no array

dtype('int64')

In [ ]:
#criar array digitando valores
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


In [ ]:
vetor1[3] #descobrindo o indice #começa contando do zero

3

In [ ]:
vetor1[0:2] #intervalo especifico

array([0, 1])

In [ ]:
print(vetor1[0:2]) #por ser print, vem sem virgula

[0 1]


In [ ]:
s = np.array(['python', 'profissional', 'java', "água"])  #criando array com string
s

array(['python', 'profissional', 'java', 'água'], dtype='<U12')

In [ ]:
s = np.array(['python', 146432315, 'profissional', 'java', "água"]) #aceita numeros e nomes, str e int
s

array(['python', '146432315', 'profissional', 'java', 'água'],
      dtype='<U21')

In [ ]:
#alterar elementos
vetor1[2] = 10 # o indice 2 passa a ser 10
vetor1

array([ 0,  1, 10,  3,  4])

In [ ]:
vetor1[0] = 'Novo elemento' #numpy trabalha apenas com matematica, não aceita str com int. Se colocar float, converte para int(caso seja)
vetor1 #aceita que acrescente numeros na array de numeros, mas não aceita que acrescente string

ValueError: ignored

In [ ]:
vetor1[0] = 45.6 #transformou float em int, que é o vetor1 original
vetor1

array([45,  1, 10,  3,  4])

In [ ]:
#matriz - numeros em forma de tabela - construindo matriz
minhaMatriz = np.array([[1, 2, 3], 
                        [4, 5, 6]]) #pode ser dado o enter
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
minhaMatriz = np.array([[1, 2, 3], [4, 5, 6]]) #sem enter o resultado é o mesmo
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#matriz construida  a partir de lista
minhaLista = [[13, 81, 22], [0, 34, 59], [21, 48, 94]]
minhaLista

[[13, 81, 22], [0, 34, 59], [21, 48, 94]]

In [ ]:
minhaLista = np.matrix(minhaLista) #para não fazer np.array, usa o matrix e o nome da lista dentro do parenteses
minhaLista

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [ ]:
#matrizes
x = np.zeros(3)
x

array([0., 0., 0.])

In [ ]:
x = np.zeros((3, 2)) #diferente do anterior, coloca 2 parentes pq tem mais de um valor
x                    #o primeiro numero as linhas(3), o segundo as colunas(2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
x[0] = 10 #teste-exercicio##alterando indice#
x

array([[10., 10.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [ ]:
x = np.ones((5, 3)) #ones
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [ ]:
m = np.ones((4, 4))*8 #criando 4X4 com numeros 8
m                 #o * não multiplica por 8, apenas repete a quantidade de vezes.

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [ ]:
#matrizes    #formas diferentes de fazer a diagonal
#formar diagonal
z = np.diag(np.array([1, 2, 3, 4, 5, 6])) #1 ao 6 na diagonal 
z                                       #nesse caso, no formação do array, escreve antes np.diag

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
#fomar matrizes
y = np.eye(5) #mais uma maneira de diagonal
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#determinar tipo int
y = np.eye(5, dtype = int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
#shape
np.shape(minhaMatriz) #joga shape pra saber o tamanho de linhas e colunas


(2, 3)

In [ ]:
#ou
minhaMatriz.shape

(2, 3)

In [ ]:
#tipo da matriz #duas formas
type(minhaMatriz) #saber o tipo

numpy.ndarray

In [ ]:
minhaMatriz.dtype #saber o que  tem dentro

dtype('int64')

In [ ]:
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#selecionar elemento
minhaMatriz[1, 1] 
#linha e coluna# primeiro numero a linha, segundo numero a coluna
##a linha começa da esquerda para direita. A coluna vem de cima para baixo.
#linha 0(1, 2, 3), 
#linha 1(4, 5, 6)
#coluna 0(1, ) coluna 1 (2, ) coluna2(3 )
#        (4, )          (5, )        (6 )

5

In [ ]:
print(minhaMatriz[0,:]) #imprimiu toda linha
#se tirar a virgula e deixar apenas pontos, imprime como fatiamento.
#com virgula imprime as posições

[1 2 3]


In [ ]:
#sem virgula e com virgula
print(minhaMatriz[:1])#sem virgula o 1 é o stop, imrpimiu a linha 0
print(minhaMatriz[:,1])#com virgula imprimiu a coluna 1, não é o stop.

[[1 2 3]]
[2 5]


In [ ]:
print(minhaMatriz[:,2])

[3 6]


In [ ]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#somando
np.sum(meuArray)

36

In [ ]:
np.prod(meuArray) #produto #multiplica- como tem um 0 dentro do array, sempre vai ser 0

0

In [ ]:
np.cumsum(meuArray) #somando indice por indice

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [ ]:
#valor maxim oe valor minimo
meuArray.min()


0

In [ ]:
meuArray.max()

8

In [ ]:
#media dos valores
np.mean(meuArray) #36 dividido por 9

4.0

In [ ]:
np.median(meuArray) #média

4.0

In [ ]:
np.var(meuArray) #variância

6.666666666666667

In [ ]:
np.std(meuArray) #desvio padrão

2.581988897471611

In [ ]:
#desafio de sala (1)
#(1)criar array unidimensional com 20 elementos
arraySala = np.arange(1, 21, 1) 
arraySala

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#(2)varrer array e achar apenas o numeros pares
arraySala[2::2]#(2)pares


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arraySala[1::2] #(3)os impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#(4) obter: média, soma, produto, variância e desvio padrão
print(np.median(arraySala)) #media
print(np.sum(arraySala)) #soma
print(np.prod(arraySala)) #produto
print(np.var(arraySala)) #variância
print(np.std(arraySala)) #desvio padrão

10.5
210
2432902008176640000
33.25
5.766281297335398


In [ ]:
#(5)saber se valores são maiores que 5
for n in arraySala:
  if n <= 5:
    print("Esse número não é maior que 5: ", n)
  elif n > 5:
    print("Esse número é maior que 5: ", n)
#(6)obter valores maiores que 5
for nMaior in arraySala:
  if nMaior > 5:
    print("Valor maior que 5: ", nMaior)

Esse número não é maior que 5:  1
Esse número não é maior que 5:  2
Esse número não é maior que 5:  3
Esse número não é maior que 5:  4
Esse número não é maior que 5:  5
Esse número é maior que 5:  6
Esse número é maior que 5:  7
Esse número é maior que 5:  8
Esse número é maior que 5:  9
Esse número é maior que 5:  10
Esse número é maior que 5:  11
Esse número é maior que 5:  12
Esse número é maior que 5:  13
Esse número é maior que 5:  14
Esse número é maior que 5:  15
Esse número é maior que 5:  16
Esse número é maior que 5:  17
Esse número é maior que 5:  18
Esse número é maior que 5:  19
Esse número é maior que 5:  20
Valor maior que 5:  6
Valor maior que 5:  7
Valor maior que 5:  8
Valor maior que 5:  9
Valor maior que 5:  10
Valor maior que 5:  11
Valor maior que 5:  12
Valor maior que 5:  13
Valor maior que 5:  14
Valor maior que 5:  15
Valor maior que 5:  16
Valor maior que 5:  17
Valor maior que 5:  18
Valor maior que 5:  19
Valor maior que 5:  20
